version: '3.5'
services: 
  app:    
    container_name: Dextra_SpringBoot
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/dextrachallenge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TZ: GMT-3
    volumes:
      - "./:/app"
      - ~/.m2:/root/.m2
    working_dir: "/app"  
    command: mvn clean spring-boot:run
    depends_on:
      - db
  db:
    image: "postgres"
    container_name: PostgresSQL
    ports:
      - "5432:5432"    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dextrachallenge      
      TZ: GMT-3