/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Aluno;
import model.dao.AlunoDAO;

/**
 *
 * @author eduma
 */
public class TelaPesquisaAlunos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMostraAlunos
     */
    public TelaPesquisaAlunos() {
        initComponents();
    }
    
    
    public void readJTableAll(){
        DefaultTableModel modelo = (DefaultTableModel) jTAlunos.getModel();
        
        modelo.setNumRows(0);
        
        AlunoDAO alunoDao = new AlunoDAO();
        
        for(Aluno aluno: alunoDao.readAll()){
            modelo.addRow(new Object[]{
                aluno.getCodigo(),
                aluno.getNome()
            
        });}
        
    }
    public void readJTableCodigo(){
        
        if (jFCodigoAluno.getText().trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "É necessário informar um código válido!");
        }
        else{
            DefaultTableModel modelo = (DefaultTableModel) jTAlunos.getModel();
        
        modelo.setNumRows(0);
        
        AlunoDAO alunoDao = new AlunoDAO();
        
        Aluno aluno = new Aluno();
        
        aluno.setCodigo(Integer.parseInt(jFCodigoAluno.getText()));
       
        alunoDao.readCodigo(aluno);
            modelo.addRow(new Object[]{
                aluno.getCodigo(),
                aluno.getNome()
            
        });
        }
        
    }
    public void readJTableNome(){
        
        if (jTFNomeAluno.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "É necessário informar um nome válido!");
        }
        else{
            
            DefaultTableModel modelo = (DefaultTableModel) jTAlunos.getModel();
        
        modelo.setNumRows(0);
        
        AlunoDAO alunoDao = new AlunoDAO();
        
        Aluno aluno = new Aluno();
        
        aluno.setNome(jTFNomeAluno.getText());
       
        alunoDao.readNome(aluno);
            modelo.addRow(new Object[]{
                aluno.getCodigo(),
                aluno.getNome()
            
        });
        }
        
    }
    
    public JButton getButtonEdit(){
        return jBEdit;
    }
    
    public JLabel getLabelEdit(){
        return jLEdit;
    }
    
    public JLabel getlaLabelDel(){
        return jLDel;
    }
    
    public JButton getButtonDel(){
        return jBDel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlunos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jFCodigoAluno = new javax.swing.JTextField();
        jTFNomeAluno = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBEdit = new javax.swing.JButton();
        jLEdit = new javax.swing.JLabel();
        jLDel = new javax.swing.JLabel();
        jBDel = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alunos");

        jLabel1.setText("Alunos Cadastrados");

        jTAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTAlunos);

        jButton1.setText("Exibir Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisar Aluno:");

        jFCodigoAluno.setText("Código do Aluno");
        jFCodigoAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFCodigoAlunoKeyPressed(evt);
            }
        });

        jTFNomeAluno.setText("Nome do Aluno");
        jTFNomeAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNomeAlunoKeyPressed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jBEdit.setText("Atualizar");
        jBEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditActionPerformed(evt);
            }
        });

        jLEdit.setText("Selecione um Aluno para Editar");

        jLDel.setText("Selecione um Aluno para Excluir");

        jBDel.setText("Deletar");
        jBDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jFCodigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDel)
                            .addComponent(jLEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBDel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 37, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jLEdit)
                    .addComponent(jBEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLDel)
                        .addComponent(jBDel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFCodigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        readJTableAll();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        readJTableCodigo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        readJTableNome();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditActionPerformed
        // TODO add your handling code here:
        
        if(jTAlunos.getSelectedRow() != -1){
        
        Aluno aluno = new Aluno();
        AlunoDAO alunoDAO = new AlunoDAO();
        
        aluno.setNome(jTFNomeAluno.getText());
        aluno.setCodigo((int)jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 0));

        alunoDAO.update(aluno);
        
        readJTableAll();
        
        } else {
            JOptionPane.showMessageDialog(null, "Para efetuar esta ação selecione o aluno a ser alterado.");
        }
    }//GEN-LAST:event_jBEditActionPerformed

    private void jTAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAlunosMouseClicked
        // TODO add your handling code here:
        
        if(jTAlunos.getSelectedRow() != -1){
            
            jFCodigoAluno.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 0).toString());
            jTFNomeAluno.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 1).toString());
        }
        
    }//GEN-LAST:event_jTAlunosMouseClicked

    private void jBDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDelActionPerformed
        // TODO add your handling code here:
        
        Aluno aluno = new Aluno();
        AlunoDAO alunoDao = new AlunoDAO();
        
        if(jTAlunos.getSelectedRow() != -1){
            
            aluno.setCodigo((int)jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 0));
            
            alunoDao.delete(aluno);
            
            readJTableAll();
            
        }
        else {
            JOptionPane.showMessageDialog(null, "Para efetuar esta ação selecione o aluno a ser removido.");
        }
    }//GEN-LAST:event_jBDelActionPerformed

    private void jFCodigoAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFCodigoAlunoKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            readJTableCodigo();
        }
        
    }//GEN-LAST:event_jFCodigoAlunoKeyPressed

    private void jTFNomeAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNomeAlunoKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            readJTableNome();
        }
        
    }//GEN-LAST:event_jTFNomeAlunoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDel;
    private javax.swing.JButton jBEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jFCodigoAluno;
    private javax.swing.JLabel jLDel;
    private javax.swing.JLabel jLEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAlunos;
    private javax.swing.JTextField jTFNomeAluno;
    // End of variables declaration//GEN-END:variables
}
