/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import model.bean.Aluno;
import model.bean.Curso;
import model.dao.AlunoDAO;
import model.dao.CursoDAO;

/**
 *
 * @author eduma
 */
public class TelaPesquisaCursos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMostraAlunos
     */
    public TelaPesquisaCursos() {
        initComponents();
    }
    
    
    public void readJTableAll(){
        DefaultTableModel modelo = (DefaultTableModel) jTCursos.getModel();
        
        modelo.setNumRows(0);
        
        CursoDAO cursoDao = new CursoDAO();
        
        for(Curso curso: cursoDao.readAll()){
            modelo.addRow(new Object[]{
                curso.getCodigo(),
                curso.getDescricao(),
                curso.getEmenta()
            
        });}
        
    }
    public void readJTableCodigo(){
        
        if (jFCodigoCurso.getText().trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "É necessário informar um código válido!");
        }
        else{
            DefaultTableModel modelo = (DefaultTableModel) jTCursos.getModel();
        
        modelo.setNumRows(0);
        
        CursoDAO cursoDao = new CursoDAO();
        
        Curso curso = new Curso();
        
        curso.setCodigo(Integer.parseInt(jFCodigoCurso.getText()));
       
        cursoDao.readCodigo(curso);
            modelo.addRow(new Object[]{
                curso.getCodigo(),
                curso.getDescricao(),
                curso.getEmenta()
            
        });
        }
        
    }
    public void readJTableDescricao(){
        
        if (jTFDescricaoCurso.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "É necessário informar uma descrição válida!");
        }
        else{
            
            DefaultTableModel modelo = (DefaultTableModel) jTCursos.getModel();
        
        modelo.setNumRows(0);
        
        CursoDAO cursoDao = new CursoDAO();
        
        Curso curso = new Curso();
        
        curso.setDescricao(jTFDescricaoCurso.getText());
       
        cursoDao.readDescricao(curso);
            modelo.addRow(new Object[]{
                curso.getCodigo(),
                curso.getDescricao(),
                curso.getEmenta()
            
        });
        }   
        
    }
    
    public JButton getButtonEdit(){
        return jBEdit;
    }
    
    public JLabel getLabelEdit(){
        return jLEdit;
    }
    
    public JLabel getLabelDel(){
        return JLabelDeletar;
    }
    
    public JButton getButtonDel(){
        return jBDeletar;
    }
    
    public JScrollPane getTextEdit(){
        return jScrollPane2;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCursos = new javax.swing.JTable();
        jBTodosCursos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jFCodigoCurso = new javax.swing.JTextField();
        jTFDescricaoCurso = new javax.swing.JTextField();
        jBCodigoCurso = new javax.swing.JButton();
        jBDescricaoCurso = new javax.swing.JButton();
        jLEdit = new javax.swing.JLabel();
        jBEdit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTEmenta = new javax.swing.JTextArea();
        JLabelDeletar = new javax.swing.JLabel();
        jBDeletar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cursos");

        jLabel1.setText("Cursos Cadastrados");

        jTCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Ementa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTCursos);

        jBTodosCursos.setText("Exibir Todos");
        jBTodosCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTodosCursosActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisar Curso:");

        jFCodigoCurso.setText("Código do Curso");
        jFCodigoCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFCodigoCursoKeyPressed(evt);
            }
        });

        jTFDescricaoCurso.setText("Descrição do Curso");
        jTFDescricaoCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDescricaoCursoKeyPressed(evt);
            }
        });

        jBCodigoCurso.setText("Buscar");
        jBCodigoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCodigoCursoActionPerformed(evt);
            }
        });

        jBDescricaoCurso.setText("Buscar");
        jBDescricaoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescricaoCursoActionPerformed(evt);
            }
        });

        jLEdit.setText("Selecione um Curso para Editar");

        jBEdit.setText("Atualizar");
        jBEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditActionPerformed(evt);
            }
        });

        jTEmenta.setColumns(20);
        jTEmenta.setRows(5);
        jTEmenta.setText("Ementa do Curso");
        jScrollPane2.setViewportView(jTEmenta);

        JLabelDeletar.setText("Selecione um Curso para Deletar");

        jBDeletar.setText("Deletar");
        jBDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTodosCursos)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelDeletar)
                            .addComponent(jLEdit)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jFCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFDescricaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBDescricaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBDeletar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jBTodosCursos))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCodigoCurso))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFDescricaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBDescricaoCurso)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBDeletar)
                            .addComponent(JLabelDeletar)))
                    .addComponent(jLEdit))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTodosCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTodosCursosActionPerformed
        // TODO add your handling code here:
        
        readJTableAll();
        
    }//GEN-LAST:event_jBTodosCursosActionPerformed

    private void jBCodigoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCodigoCursoActionPerformed
        // TODO add your handling code here:
        
        readJTableCodigo();
    }//GEN-LAST:event_jBCodigoCursoActionPerformed

    private void jBDescricaoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDescricaoCursoActionPerformed
        // TODO add your handling code here:
        
        readJTableDescricao();
        
    }//GEN-LAST:event_jBDescricaoCursoActionPerformed

    private void jTCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCursosMouseClicked
        // TODO add your handling code here:
        
        if(jTCursos.getSelectedRow() != -1){
            
            jFCodigoCurso.setText(jTCursos.getValueAt(jTCursos.getSelectedRow(), 0).toString());
            jTFDescricaoCurso.setText(jTCursos.getValueAt(jTCursos.getSelectedRow(), 1).toString());
            jTEmenta.setText(jTCursos.getValueAt(jTCursos.getSelectedRow(), 2).toString());
        }
        
    }//GEN-LAST:event_jTCursosMouseClicked

    private void jBEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditActionPerformed
        // TODO add your handling code here:
        
        if(jTCursos.getSelectedRow() != -1){
            
            Curso curso = new Curso();
            CursoDAO cursoDao = new CursoDAO();
                    
            curso.setCodigo((int)jTCursos.getValueAt(jTCursos.getSelectedRow(), 0));
            curso.setDescricao(jTFDescricaoCurso.getText());
            curso.setEmenta(jTEmenta.getText());
            
            cursoDao.update(curso);
            
            readJTableAll();
            
        }
        
    }//GEN-LAST:event_jBEditActionPerformed

    private void jBDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeletarActionPerformed
        // TODO add your handling code here:
        
        Curso curso = new Curso();
        CursoDAO cursoDao = new CursoDAO();
        
        if(jTCursos.getSelectedRow() != -1){
            
            curso.setCodigo((int)jTCursos.getValueAt(jTCursos.getSelectedRow(), 0));
            
            cursoDao.delete(curso);
            
            readJTableAll();
            
        }else {
            JOptionPane.showMessageDialog(null, "Para efetuar esta ação selecione o aluno a ser removido.");
        }
        
        
    }//GEN-LAST:event_jBDeletarActionPerformed

    private void jFCodigoCursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFCodigoCursoKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            readJTableCodigo();
        }
        
    }//GEN-LAST:event_jFCodigoCursoKeyPressed

    private void jTFDescricaoCursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDescricaoCursoKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            readJTableDescricao();
        }
        
    }//GEN-LAST:event_jTFDescricaoCursoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelDeletar;
    private javax.swing.JButton jBCodigoCurso;
    private javax.swing.JButton jBDeletar;
    private javax.swing.JButton jBDescricaoCurso;
    private javax.swing.JButton jBEdit;
    private javax.swing.JButton jBTodosCursos;
    private javax.swing.JTextField jFCodigoCurso;
    private javax.swing.JLabel jLEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTCursos;
    private javax.swing.JTextArea jTEmenta;
    private javax.swing.JTextField jTFDescricaoCurso;
    // End of variables declaration//GEN-END:variables
}
